name: frontend
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - '.github/workflows/frontend.yml'
      - '.eslintrc.js'
      - 'package.json'
      - 'next.config.js'
  pull_request:
    paths:
      - 'src/**'
      - 'public/**'
      - '.github/workflows/frontend.yml'
      - '.eslintrc.js'
      - 'package.json'
      - 'next.config.js'
jobs:
  lint_test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint
      - run: yarn test
